https://www.hackerrank.com/challenges/full-score/problem?isFullScreen=true 

SELECT S.HACKER_ID, 
       NAME
FROM SUBMISSIONS S
INNER JOIN CHALLENGES C ON S.CHALLENGE_ID = C.CHALLENGE_ID
INNER JOIN HACKERS H ON H.HACKER_ID = S.HACKER_ID
INNER JOIN DIFFICULTY D ON D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
WHERE D.SCORE = S.SCORE
GROUP BY S.HACKER_ID, NAME
HAVING COUNT(NAME) > 1
ORDER BY COUNT(NAME) DESC, S.HACKER_ID;
