WITH A AS (
    SELECT START_DATE 
    FROM PROJECTS 
    WHERE START_DATE NOT IN (SELECT END_DATE FROM PROJECTS)
    ORDER BY START_DATE ASC
), B AS (    
    SELECT END_DATE 
    FROM PROJECTS 
    WHERE END_DATE NOT IN (SELECT START_DATE FROM PROJECTS)
    ORDER BY END_DATE ASC
)
SELECT START_DATE, MIN(END_DATE) AS END_DATE
FROM A, B
WHERE START_DATE < END_DATE
GROUP BY START_DATE
ORDER BY (END_DATE - START_DATE), START_DATE;
