SELECT 
    MAX(D), 
    MAX(P), 
    MAX(S), 
    MAX(A)
FROM
(
    SELECT 
        CASE WHEN OCCUPATION = 'Doctor' THEN NAME END AS D,
        CASE WHEN OCCUPATION = 'Professor' THEN NAME END AS P,
        CASE WHEN OCCUPATION = 'Singer' THEN NAME END AS S,
        CASE WHEN OCCUPATION = 'Actor' THEN NAME END AS A,
        ROW_NUMBER() OVER (PARTITION BY OCCUPATION ORDER BY NAME) AS R
    FROM 
        OCCUPATIONS
) T1
GROUP BY R;
